name = "GregRegistry"
uuid = "ce8661f2-6496-4f32-bd74-1d3f42d63d43"
repo = "https://github.com/grlap/Registry"
description = "Private repository"

[packages]
d59d01c2-cedb-43fa-bb24-e6eaeb189957 = { name = "Nghttp2", path = "N/Nghttp2" }
