name = "GregRegistry"
uuid = "ce8661f2-6496-4f32-bd74-1d3f42d63d43"
repo = "https://github.com/grlap/Registry"
description = "Private repository"

[packages]
4d8831e6-92b7-49fb-bdf8-b643e874388c = { name = "OpenSSL", path = "O/OpenSSL" }
